### ISSUE TITLE
Remove username/password login?

### ISSUE THREAD

**Issue by alexmcmillan** [jstogether/jstogether#7]
Now that we have github working via oauth, and as github is a requirement for this project, I reckon we should bin the local strategy (username/password).

Means we aren't responsible for peoples passwords etc.  And sessions persist.

**Comment by jephillips** [comment]
+1

**Comment by jchatkinson** [comment]
Good idea. On the front page maybe we could have a message "JSTogether makes extensive use of Github. If you don't have an account, you need to [create one](https://github.com/join) first"

or something like that

**Comment by alexmcmillan** [comment]
Okay, I've commented out the login/username fields for now, but the functionality is still there.

At the moment we're exposing the `AppActions` module to the `window`, so if you're devving on localhost and you want to login, just fire up the console and use:

```
AppActions.login({
    username: 'your username',
    password: 'your password'
});
```

Or

```
AppActions.register({
    username: 'something',
    password: 'something else'
});
```
